name: simpleIO
version: 0.0.0
homepage: https://github.com/morloc-lib/simpleIO
synopsis: Simple functions for IO
description:
  This package offers very simple IO operations, such as reading and writing
  files. When Morloc's effect system is added, this library will be deprecated
  or rewritten.
category: language-base
license: MIT
author: "Zebulun Arendsee"
maintainer: "zbwrnz@gmail.com"
github: https://github.com/morloc-lib/simpleIO
bug-reports: https://github.com/morloc-lib/simpleIO
